### PR TITLE
Add verify_eigrp_interfaces_peers API to verify.py ios/iosxe eigrp protocol

### PR DESCRIPTION
**Pull request by cherifimehdi**
Hello,

I added verify_eigrp_interfaces_peers API to verify.py (my previous contribution) for ios/iosxe eigrp protocol.

I added the tests folder verify_eigrp_interfaces_peers at pkgs/sdk-pkg/src/genie/libs/sdk/apis/tests/iosxe/eigrp/verify

I added the changelog_add_verify_eigrp_interfaces_peers_apis_202417071905 file at pkgs/sdk-pkg/changelog folder

Thank you for reviewing my contribution

### CODE REVIEW

**Comment by cherifimehdi** [comment]
Hi @lsheikal  @ThomasJRyan  I added a PR for Cisco pyATS API for EIGRP verify.py.
Thank you for reviewing my PR

**Review by ThomasJRyan — APPROVED** [review]
Thank you for the contribution! It's a little heavy handed on some Python quirks, but functionally I don't see anything wrong with it

**Comment by cherifimehdi** [comment]
> Thank you for the contribution! It's a little heavy handed on some Python quirks, but functionally I don't see anything wrong with it

Hi @ThomasJRyan  thank you for reviewing and accepting my PR!  It is not quirks but innovation

**Comment by ThomasJRyan** [comment]
> > Thank you for the contribution! It's a little heavy handed on some Python quirks, but functionally I don't see anything wrong with it
> 
> Hi @ThomasJRyan thank you for reviewing and accepting my PR! It is not quirks but innovation

We'll have to agree to disagree on that one 😂 Thank you again for the contribution!

**Pull request merged**
