### PR TITLE
Adding missing documentation parameters

### PR DESCRIPTION
**Pull request by joabda**
**Issue Description:**
In the [pubhub documentation for create_dhcp_pool](https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/apis/create_dhcp_pool) the lease parameters are missing. 

**Changes:**
I proposed to replace the current function's documentation with the following:
```python
def create_dhcp_pool(
    device, pool_name, network, mask, router_id,lease_days,lease_hrs,lease_mins
):
    """ Create DHCP pool
        Args:
            device ('obj'): device to use
            pool_name ('str'): name of the pool to be created
            network ('str'): IP of the network pool
            mask ('str'): Subnet mask of the network pool
            router_id ('str'): Default router ID
            lease_days ('str'): Number of days for the lease
            lease_hrs ('str'): Number of hours for the lease
            lease_mins ('str'): Number of minutes for the lease
        Returns:
            None
        Raises:
            SubCommandFailure: Failed creating dhcp pool
    """
```

**Unit Testing:**
None required, changes only affect comment part.

### CODE REVIEW

**Comment by joabda** [comment]
@GerriorL what about this failing run?

**Comment by GerriorL** [comment]
> @GerriorL what about this failing run?

We don't support 3.7 anymore

**Comment by joabda** [comment]
@GerriorL Anything required on my side to merge this?

**Comment by omehrabi** [comment]
could you merge master and push again

**Comment by joabda** [comment]
@omehrabi Done

**Review by omehrabi — APPROVED** [review]

**Pull request merged**
